Document: rtchmod
Title: Debian rtchmod Manual
Author: <insert document author here>
Abstract: This manual describes what rtchmod is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtchmod/rtchmod.sgml.gz

Format: postscript
Files: /usr/share/doc/rtchmod/rtchmod.ps.gz

Format: text
Files: /usr/share/doc/rtchmod/rtchmod.text.gz

Format: HTML
Index: /usr/share/doc/rtchmod/html/index.html
Files: /usr/share/doc/rtchmod/html/*.html
